import hashlib
import json
import re
import sqlite3
import time
import uuid
from typing import Any

from app.audit import AuditRepository
from app.catalog import CatalogError, MetadataCatalog
from app.evidence import ResultEvidenceBuilder
from app.executor import ExecutionResult, QueryExecutionError, QueryTimeoutError, SQLiteExecutor
from app.llm import (
    LLMConfigurationError,
    LLMInvalidResponseError,
    LLMPlanSchemaError,
    LLMResponseError,
    LLMReviewSchemaError,
    LLMTimeoutError,
    LLMUpstreamUnavailableError,
    QueryLLM,
)
from app.llm_trace import llm_trace_context
from app.models import Coverage, QueryData, QueryPlan, QueryRequest, ResultSet, SourceInfo, ToolResponse
from app.sql_guard import SqlGuard, SqlValidationError, ValidatedSql
from app.stage_timing import StageTimingRepository


class QueryTotalTimeoutError(RuntimeError):
    pass


class QueryService:
    """Explicit, bounded SQL generation/review state machine.

    Review models provide opinions only. All SQL changes are generated by the SQL
    generator and revalidated by the deterministic guard before execution.
    """

    def __init__(
        self,
        catalog: MetadataCatalog,
        llm: QueryLLM,
        guard: SqlGuard,
        executor: SQLiteExecutor,
        audit: AuditRepository,
        stage_timing: StageTimingRepository | None = None,
        diagnostics_enabled: bool = False,
        max_sql_repair_attempts: int = 1,
        max_semantic_rewrite_attempts: int = 1,
        max_result_requery_attempts: int = 1,
        total_timeout_seconds: float = 240.0,
    ) -> None:
        self.catalog = catalog
        self.llm = llm
        self.guard = guard
        self.executor = executor
        self.audit = audit
        self.stage_timing = stage_timing
        self.diagnostics_enabled = diagnostics_enabled
        # Guard repair and semantic revision share one budget by design.
        self.max_sql_modification_attempts = min(
            max_sql_repair_attempts, max_semantic_rewrite_attempts
        )
        self.max_result_requery_attempts = max_result_requery_attempts
        self.total_timeout_seconds = total_timeout_seconds
        self.evidence_builder = ResultEvidenceBuilder()

    def _new_diagnostics(self) -> dict[str, Any] | None:
        if not self.diagnostics_enabled:
            return None
        return {
            "stage": "routing",
            "plan": {"status": "not_started"},
            "sql_generation": [],
            "sql_guard": [],
            "pre_execution_review": [],
            "execution": [],
            "result_review": [],
            "fallback": {"attempted": False, "exact_question_match": False, "used": False},
        }

    def _normalize_plan(self, plan: QueryPlan, question: str, route) -> QueryPlan:
        """Bind the immutable request text and enforce the published table boundary."""
        tables = set(plan.table_hints)
        if route is not None and route.required_tables:
            tables.update(route.required_tables)
        if not tables.issubset(self.catalog.allowed_tables):
            raise CatalogError("查询规划引用了未发布的数据表")
        if len(tables) > 4:
            raise CatalogError("查询规划引用的数据表超过上限")
        return plan.model_copy(
            update={
                "original_question": question,
                "table_hints": sorted(tables),
                "required_outputs": plan.required_outputs or [question],
            }
        )

    async def query(self, request: QueryRequest) -> ToolResponse:
        request_id = f"qry_{uuid.uuid4().hex}"
        started = time.monotonic()
        deadline = started + self.total_timeout_seconds
        audit_base = {"request_id": request_id, "question_sha256": hashlib.sha256(request.question.encode("utf-8")).hexdigest()}
        diagnostics = self._new_diagnostics()
        stage = "routing"
        try:
            with self._measure_stage(request_id, stage):
                route = self.catalog.routing_decision(request.question)
                concept_clarification = self.catalog.concept_clarification(
                    request.question
                )
            if route is not None and route.action in {"reject_scope", "reject_capability"}:
                return self._failure(
                    request_id,
                    "QUERY_NOT_SUPPORTED" if route.action == "reject_scope" else "CAPABILITY_NOT_SUPPORTED",
                    route.message or "当前数据范围或已发布口径不支持该查询",
                    False, audit_base, started, list(route.required_tables), stage, diagnostics,
                )

            if concept_clarification is not None:
                return self._failure(
                    request_id,
                    "CLARIFICATION_REQUIRED",
                    concept_clarification["message"],
                    False,
                    audit_base,
                    started,
                    list(route.required_tables) if route is not None else [],
                    stage,
                    diagnostics,
                )

            deterministic_route = bool(
                route is not None
                and route.action == "allow"
                and route.required_tables
            )
            if deterministic_route:
                stage = "planning_deterministic_route"
                with self._measure_stage(request_id, stage):
                    plan = QueryPlan(
                        original_question=request.question,
                        query_type="aggregation",
                        table_hints=list(route.required_tables),
                        required_outputs=[request.question],
                        business_objects=[],
                        time_requirements=[],
                        presentation_requirements=[],
                    )
                planning_mode = "deterministic_route"
            else:
                stage = "planning"
                self._ensure_within_total_timeout(deadline)
                self._diag(diagnostics, "plan", {"status": "started"}, stage)
                with self._measure_stage(request_id, stage):
                    with llm_trace_context(request_id, stage):
                        plan = await self.llm.plan(
                            request.question, self.catalog.build_planning_context(route)
                        )
                planning_mode = "llm"
            plan = self._normalize_plan(plan, request.question, route)
            audit_base.update(
                {
                    "planning_mode": planning_mode,
                    "query_plan": plan.model_dump(exclude={"original_question"}),
                }
            )
            self._diag(
                diagnostics,
                "plan",
                {
                    "status": "passed",
                    "planning_mode": planning_mode,
                    "table_hints": plan.table_hints,
                    "original_question_preserved": True,
                },
                stage,
            )
            if plan.requires_clarification:
                resolved_values = self.catalog.resolved_categorical_values(
                    request.question, plan.table_hints
                )
                if resolved_values:
                    stage = "planning_categorical_retry"
                    self._ensure_within_total_timeout(deadline)
                    retry_context = "\n".join(
                        [
                            self.catalog.build_planning_context(route),
                            "服务端已根据受控表卡唯一确认以下分类口径。不得再要求用户确认这些数据库内部枚举；请据此重新规划：",
                            json.dumps(resolved_values, ensure_ascii=False),
                        ]
                    )
                    with self._measure_stage(request_id, stage):
                        with llm_trace_context(request_id, stage):
                            plan = await self.llm.plan(request.question, retry_context)
                    plan = self._normalize_plan(plan, request.question, route)
                    audit_base["query_plan"] = plan.model_dump(
                        exclude={"original_question"}
                    )
                    self._diag(
                        diagnostics,
                        "plan_categorical_retry",
                        {
                            "status": "passed",
                            "table_hints": plan.table_hints,
                            "resolved_value_count": len(resolved_values),
                        },
                        stage,
                    )
            if plan.requires_clarification:
                return self._failure(
                    request_id, "CLARIFICATION_REQUIRED", plan.clarification_question or "请补充查询所需条件。",
                    False, audit_base, started, plan.table_hints, stage, diagnostics,
                )

            if plan.original_question != request.question:
                raise CatalogError("查询计划未保留原始用户问题")

            context = self.catalog.build_sql_context(request.question, plan.table_hints, route)
            contract = self.catalog.expected_result_contract(request.question, plan.table_hints, plan, route)
            modifications = 0
            stage = "sql_generation_initial"
            self._ensure_within_total_timeout(deadline)
            candidate_sql = await self._generate_sql(request_id, stage, request.question, plan, context, "initial")
            self._append_diag(diagnostics, "sql_generation", {"stage": stage, "task_mode": "initial", "status": "generated"}, stage)
            validated, candidate_sql, modifications = await self._validate_or_modify(
                request_id, request.question, plan, context, candidate_sql, modifications, diagnostics
            )

            stage = "pre_execution_review_1"
            self._ensure_within_total_timeout(deadline)
            review = await self._pre_review(request_id, stage, request.question, plan, context, validated.sql, contract)
            self._append_diag(diagnostics, "pre_execution_review", {"stage": stage, "decision": review.decision}, stage)
            if review.decision != "pass":
                response, continuation = await self._handle_pre_review(
                    request_id, request.question, plan, context, contract, validated, candidate_sql,
                    review, modifications, audit_base, started, diagnostics,
                )
                if response is not None:
                    return response
                validated, candidate_sql, modifications = continuation

            stage = "execution_primary"
            self._ensure_within_total_timeout(deadline)
            primary = await self._execute(request_id, validated, diagnostics, stage)
            sources = self._sources(validated.tables)
            primary_evidence = self.evidence_builder.build(
                primary, sources=sources, applied_scope=contract["scope"],
                field_labels=self.catalog.result_field_labels(validated.tables),
            )
            stage = "result_review_1"
            self._ensure_within_total_timeout(deadline)
            result_review = await self._result_review(request_id, stage, request.question, plan, contract, primary_evidence.model_dump())
            self._append_diag(diagnostics, "result_review", {"stage": stage, "decision": result_review.decision}, stage)
            if result_review.decision == "answer":
                return self._success(
                    request_id, request.question, plan, route, validated.tables, primary, sources,
                    limitations=result_review.answer_limitations + primary_evidence.limitations,
                    diagnostics=diagnostics, audit_base=audit_base, started=started,
                )
            if result_review.decision == "clarification":
                return self._failure(request_id, "CLARIFICATION_REQUIRED", result_review.clarification or "请补充查询条件。", False, audit_base, started, plan.table_hints, stage, diagnostics)
            if result_review.decision == "unsupported":
                return self._failure(request_id, self._result_failure_code(result_review.result_issues), self._business_failure_message(result_review.result_issues), False, audit_base, started, plan.table_hints, stage, diagnostics)
            if self.max_result_requery_attempts < 1:
                return self._failure(request_id, "RESULT_REVIEW_EXHAUSTED", self._result_exhausted_message(result_review.result_issues), False, audit_base, started, plan.table_hints, stage, diagnostics)

            stage = "sql_result_requery_1"
            self._ensure_within_total_timeout(deadline)
            supplemental_sql = await self._generate_sql(
                request_id, stage, request.question, plan, context, "result_requery", candidate_sql,
                self._review_feedback(result_review.result_issues, result_review.required_changes),
            )
            self._append_diag(diagnostics, "sql_generation", {"stage": stage, "task_mode": "result_requery", "status": "generated"}, stage)
            supplemental_validated = self._timed_validate(
                request_id, "sql_guard_requery_1", supplemental_sql,
                plan.table_hints, request.question,
            )
            self._append_diag(diagnostics, "sql_guard", {"stage": "sql_guard_requery_1", "status": "passed", "tables": sorted(supplemental_validated.tables)}, "sql_guard_requery_1")
            stage = "execution_supplemental"
            self._ensure_within_total_timeout(deadline)
            supplemental = await self._execute(
                request_id, supplemental_validated, diagnostics, stage
            )
            all_tables = validated.tables | supplemental_validated.tables
            all_sources = self._sources(all_tables)
            supplemental_evidence = self.evidence_builder.build(
                supplemental, sources=all_sources, applied_scope=contract["scope"],
                field_labels=self.catalog.result_field_labels(supplemental_validated.tables),
            )
            stage = "result_review_2"
            self._ensure_within_total_timeout(deadline)
            final_review = await self._result_review(
                request_id, stage, request.question, plan, contract,
                self.evidence_builder.merge(primary_evidence, supplemental_evidence),
            )
            self._append_diag(diagnostics, "result_review", {"stage": stage, "decision": final_review.decision}, stage)
            if final_review.decision == "answer":
                return self._success(
                    request_id, request.question, plan, route, all_tables, primary, all_sources,
                    supplemental=supplemental,
                    limitations=final_review.answer_limitations + primary_evidence.limitations + supplemental_evidence.limitations,
                    diagnostics=diagnostics, audit_base=audit_base, started=started,
                )
            if final_review.decision == "clarification":
                return self._failure(request_id, "CLARIFICATION_REQUIRED", final_review.clarification or "请补充查询条件。", False, audit_base, started, plan.table_hints, stage, diagnostics)
            if final_review.decision == "unsupported":
                return self._failure(request_id, self._result_failure_code(final_review.result_issues), self._business_failure_message(final_review.result_issues), False, audit_base, started, plan.table_hints, stage, diagnostics)
            return self._failure(request_id, "RESULT_REVIEW_EXHAUSTED", self._result_exhausted_message(final_review.result_issues), False, audit_base, started, plan.table_hints, stage, diagnostics)
        except LLMConfigurationError:
            return self._failure(request_id, "LLM_NOT_CONFIGURED", "模型接口尚未配置。", False, audit_base, started, stage=stage, diagnostics=diagnostics)
        except LLMResponseError as exc:
            self._diag(diagnostics, "stage", stage, stage)
            if stage in {"planning", "sql_generation_initial"}:
                fallback = await self._try_exact_example_fallback(request_id, request, audit_base, started, diagnostics)
                if fallback is not None:
                    return fallback
            return self._failure(request_id, self._llm_error_code(exc, stage), self._llm_error_message(exc, stage), not isinstance(exc, (LLMPlanSchemaError, LLMReviewSchemaError)), audit_base, started, stage=stage, diagnostics=diagnostics)
        except CatalogError:
            return self._failure(request_id, "QUERY_NOT_SUPPORTED", "查询超出已发布数据范围。", False, audit_base, started, stage=stage, diagnostics=diagnostics)
        except SqlValidationError:
            fallback = await self._try_exact_example_fallback(request_id, request, audit_base, started, diagnostics) if stage in {"planning", "sql_generation_initial"} else None
            if fallback is not None:
                return fallback
            return self._failure(request_id, "SQL_VALIDATION_FAILED", "系统未能形成符合安全要求的数据查询。请明确指标、时间或对象后重试；如持续出现，请提供请求编号排查。", False, audit_base, started, stage=stage, diagnostics=diagnostics)
        except QueryTimeoutError:
            return self._failure(request_id, "QUERY_TIMEOUT", "数据查询执行时间超过限制，未返回未经审核的部分结果。请缩小时间、区县或明细范围后重试。", True, audit_base, started, stage=stage, diagnostics=diagnostics)
        except QueryTotalTimeoutError:
            return self._failure(request_id, "QUERY_TIMEOUT", "查询处理超过总时限，系统未返回未经审核的部分结果。请缩小范围后重试。", True, audit_base, started, stage=stage, diagnostics=diagnostics)
        except QueryExecutionError:
            return self._failure(request_id, "INTERNAL_ERROR", "数据库查询阶段未能完成。请确认筛选范围后重试；若持续出现，请提供请求编号排查。", False, audit_base, started, stage=stage, diagnostics=diagnostics)
        except Exception:
            return self._failure(request_id, "INTERNAL_ERROR", "查询服务处理过程中出现内部异常，未返回未经验证的数据。请稍后重试；若持续出现，请提供请求编号排查。", False, audit_base, started, stage=stage, diagnostics=diagnostics)

    async def _handle_pre_review(self, request_id, question, plan, context, contract, validated, candidate_sql, review, modifications, audit_base, started, diagnostics):
        if review.decision == "clarification":
            return self._failure(request_id, "CLARIFICATION_REQUIRED", review.clarification or "请补充查询条件。", False, audit_base, started, plan.table_hints, "pre_execution_review", diagnostics), None
        if review.decision == "unsupported":
            return self._failure(request_id, "CAPABILITY_NOT_SUPPORTED", self._business_failure_message(review.issues), False, audit_base, started, plan.table_hints, "pre_execution_review", diagnostics), None
        if modifications >= self.max_sql_modification_attempts:
            return self._failure(request_id, "PRE_EXECUTION_REVIEW_EXHAUSTED", self._pre_exhausted_message(review.issues), False, audit_base, started, plan.table_hints, "pre_execution_review", diagnostics), None
        revised_sql = await self._generate_sql(request_id, "sql_semantic_revision_1", question, plan, context, "semantic_revision", candidate_sql, self._review_feedback(review.issues, review.required_changes))
        self._append_diag(diagnostics, "sql_generation", {"stage": "sql_semantic_revision_1", "task_mode": "semantic_revision", "status": "generated"}, "sql_semantic_revision_1")
        revised = self._timed_validate(
            request_id, "sql_guard_revision_1", revised_sql,
            plan.table_hints, question,
        )
        self._append_diag(diagnostics, "sql_guard", {"stage": "sql_guard_revision_1", "status": "passed", "tables": sorted(revised.tables)}, "sql_guard_revision_1")
        second = await self._pre_review(request_id, "pre_execution_review_2", question, plan, context, revised.sql, contract)
        self._append_diag(diagnostics, "pre_execution_review", {"stage": "pre_execution_review_2", "decision": second.decision}, "pre_execution_review_2")
        if second.decision != "pass":
            if second.decision == "clarification":
                return self._failure(request_id, "CLARIFICATION_REQUIRED", second.clarification or "请补充查询条件。", False, audit_base, started, plan.table_hints, "pre_execution_review_2", diagnostics), None
            if second.decision == "unsupported":
                return self._failure(request_id, "CAPABILITY_NOT_SUPPORTED", self._business_failure_message(second.issues), False, audit_base, started, plan.table_hints, "pre_execution_review_2", diagnostics), None
            return self._failure(request_id, "PRE_EXECUTION_REVIEW_EXHAUSTED", self._pre_exhausted_message(second.issues), False, audit_base, started, plan.table_hints, "pre_execution_review_2", diagnostics), None
        return None, (revised, revised_sql, modifications + 1)

    async def _validate_or_modify(self, request_id, question, plan, context, candidate_sql, modifications, diagnostics):
        try:
            validated = self._timed_validate(
                request_id, "sql_guard_initial", candidate_sql,
                plan.table_hints, question,
            )
            self._append_diag(diagnostics, "sql_guard", {"stage": "sql_guard_initial", "status": "passed", "tables": sorted(validated.tables)}, "sql_guard_initial")
            return validated, candidate_sql, modifications
        except SqlValidationError as error:
            self._append_diag(diagnostics, "sql_guard", {"stage": "sql_guard_initial", "status": "rejected"}, "sql_guard_initial")
            if modifications >= self.max_sql_modification_attempts or not self._is_repairable_sql_error(error):
                raise
            repaired_sql = await self._generate_sql(request_id, "sql_guard_repair_1", question, plan, context, "guard_repair", candidate_sql, {"guard_error": str(error)})
            self._append_diag(diagnostics, "sql_generation", {"stage": "sql_guard_repair_1", "task_mode": "guard_repair", "status": "generated"}, "sql_guard_repair_1")
            validated = self._timed_validate(
                request_id, "sql_guard_repair_validation_1", repaired_sql,
                plan.table_hints, question,
            )
            self._append_diag(diagnostics, "sql_guard", {"stage": "sql_guard_repair_1", "status": "passed", "tables": sorted(validated.tables)}, "sql_guard_repair_1")
            return validated, repaired_sql, modifications + 1

    async def _generate_sql(self, request_id, stage, question, plan, context, task_mode, previous_sql=None, feedback=None):
        with self._measure_stage(request_id, stage):
            with llm_trace_context(request_id, stage):
                return await self.llm.generate_sql(question, plan, context, task_mode=task_mode, previous_sql=previous_sql, feedback=feedback)

    async def _pre_review(self, request_id, stage, question, plan, context, sql, contract):
        with self._measure_stage(request_id, stage):
            with llm_trace_context(request_id, stage):
                return await self.llm.review_before_execution(question, plan, context, sql, contract)

    async def _result_review(self, request_id, stage, question, plan, contract, evidence):
        with self._measure_stage(request_id, stage):
            with llm_trace_context(request_id, stage):
                return await self.llm.review_result(question, plan, contract, evidence)

    async def _execute(
        self, request_id: str, validated: ValidatedSql, diagnostics, stage: str
    ) -> ExecutionResult:
        with self._measure_stage(request_id, stage):
            result = await self.executor.execute(validated.sql)
        self._append_diag(diagnostics, "execution", {"stage": stage, "row_count": result.row_count, "truncated": result.truncated, "duration_ms": result.duration_ms}, stage)
        return result

    def _timed_validate(self, request_id, stage, sql, table_hints, question):
        with self._measure_stage(request_id, stage):
            return self._validate_planned_sql(sql, table_hints, question)

    def _measure_stage(self, request_id, stage):
        if self.stage_timing is None:
            from contextlib import nullcontext

            return nullcontext()
        return self.stage_timing.measure(request_id, stage)

    def _success(self, request_id, question, plan, route, tables, primary, sources, *, supplemental=None, limitations=None, diagnostics, audit_base, started):
        warnings = ["RESULT_TRUNCATED"] if primary.truncated else []
        if not primary.rows:
            warnings.extend(["NO_DATA", "NO_DATA_AFTER_VALID_FILTER"])
        data = self._query_data(primary, sources)
        result_sets = [ResultSet(id="primary", purpose="主查询", data=data)]
        if supplemental is not None:
            result_sets.append(ResultSet(id="supplemental", purpose="补查", data=self._query_data(supplemental, sources)))
        response = ToolResponse(
            success=True, request_id=request_id, data=data, result_sets=result_sets, sources=sources,
            warnings=warnings, limitations=list(dict.fromkeys(limitations or [])),
            coverage=Coverage(
                applied_scope=self.catalog.data_domain()["administrative_scope"],
                dimensions=[],
                measures=[],
            ),
            answer_guidance=self.catalog.answer_guidance(question, tables, route), diagnostics=diagnostics,
        )
        self.audit.record({**audit_base, "status": "success", "query_type": plan.query_type, "tables": sorted(tables), "row_count": primary.row_count, "result_sets": len(result_sets), "duration_ms": int((time.monotonic() - started) * 1000)})
        if self.stage_timing is not None:
            self.stage_timing.record_duration(request_id, "request_total", started, status="success")
        return response

    def _query_data(self, result, sources):
        data_as_of = [source.data_as_of for source in sources if source.data_as_of]
        return QueryData(rows=result.rows, summary=dict(result.rows[0]) if len(result.rows) == 1 else {"row_count": result.row_count, "truncated": result.truncated}, schema_=result.schema, data_as_of=max(data_as_of) if data_as_of else None, result_status="data_found" if result.rows else "no_match", result_reason=None if result.rows else "当前合法筛选条件下未匹配到记录")

    def _sources(self, tables):
        return [SourceInfo(**item) for item in self.catalog.source_info(tables)]

    def _failure(self, request_id, code, message, retryable, audit_base, started, tables=None, stage=None, diagnostics=None):
        self.audit.record({**audit_base, "status": "failed", "error_code": code, "tables": sorted(tables or []), "stage": stage, "duration_ms": int((time.monotonic() - started) * 1000)})
        if self.stage_timing is not None:
            self.stage_timing.record_duration(request_id, "request_total", started, status="error")
        return ToolResponse.failure(request_id=request_id, code=code, message=message, retryable=retryable, diagnostics=diagnostics)

    def _validate_planned_sql(self, sql, planned_tables, question):
        validated = self.guard.validate(sql)
        if not validated.tables.issubset(set(planned_tables)):
            raise SqlValidationError("SQL 引用了规划范围外的数据表")
        scope_issues = self.catalog.scope_filter_issues(
            question, validated.sql, validated.tables
        )
        if scope_issues:
            raise SqlValidationError("；".join(scope_issues))
        return validated

    @staticmethod
    def _review_feedback(issues, changes):
        return {"issues": [item.model_dump() for item in issues], "required_changes": changes}

    @staticmethod
    def _is_repairable_sql_error(error):
        return not any(marker in str(error) for marker in ("SQL 包含禁止操作", "SQL 不允许包含注释", "只允许单条 SQL", "只允许 SELECT"))

    @staticmethod
    def _safe_business_issues(issues):
        unsafe = re.compile(r"\b(?:select|with|from|join|where|group\s+by|order\s+by|pragma|ddl)\b|\bt\d{2}_[a-z0-9_]+\b|[_`*]", re.I)
        return [item.message.strip().rstrip("。") for item in issues[:3] if item.message.strip() and len(item.message.strip()) <= 160 and not unsafe.search(item.message)]

    @classmethod
    def _business_failure_message(cls, issues):
        useful = cls._safe_business_issues(issues)
        return "当前数据或已发布口径暂不能可靠回答。" + ("原因：" + "；".join(useful) + "。" if useful else "") + "请明确查询指标、时间范围或业务口径后重试。"

    @classmethod
    def _pre_exhausted_message(cls, issues):
        useful = cls._safe_business_issues(issues)
        return "系统已按审核意见修正一次查询，但仍无法形成可靠结果。" + ("原因：" + "；".join(useful) + "。" if useful else "") + "当前未执行该查询，请调整问题范围或提供请求编号排查。"

    @classmethod
    def _result_exhausted_message(cls, issues):
        useful = cls._safe_business_issues(issues)
        return "已完成一次补查，但返回数据仍不足以支撑可靠结论。" + ("限制：" + "；".join(useful) + "。" if useful else "") + "请调整查询范围或补充数据口径。"

    @staticmethod
    def _result_failure_code(issues) -> str:
        return (
            "DATA_QUALITY_LIMITATION"
            if any(item.code == "DATA_QUALITY_LIMITATION" for item in issues)
            else "CAPABILITY_NOT_SUPPORTED"
        )

    @staticmethod
    def _llm_error_code(exc, stage):
        if isinstance(exc, LLMTimeoutError): return "LLM_TIMEOUT"
        if isinstance(exc, LLMUpstreamUnavailableError): return "LLM_UPSTREAM_UNAVAILABLE"
        if isinstance(exc, LLMPlanSchemaError): return "LLM_PLAN_SCHEMA_INVALID"
        if isinstance(exc, LLMReviewSchemaError): return "REVIEW_SCHEMA_INVALID"
        if isinstance(exc, LLMInvalidResponseError): return "LLM_INVALID_JSON"
        return "PLANNING_FAILED" if stage == "planning" else "SQL_GENERATION_FAILED"

    @staticmethod
    def _llm_error_message(exc, stage):
        if isinstance(exc, LLMTimeoutError): return "模型在当前阶段响应超时，系统未执行未经审核的查询。请稍后重试或缩小范围。"
        if isinstance(exc, LLMUpstreamUnavailableError): return "模型服务当前不可用，数据查询尚未执行。请稍后重试。"
        if isinstance(exc, LLMPlanSchemaError): return "模型未按约定格式返回查询规划，数据查询尚未执行。请重试一次；若持续出现，请提供请求编号排查。"
        if isinstance(exc, LLMReviewSchemaError): return "审核模型未按约定格式返回意见，因此系统没有执行候选查询。请重试或提供请求编号排查。"
        if isinstance(exc, LLMInvalidResponseError): return "模型返回内容无法解析，系统未执行未经验证的查询。请重试一次。"
        return "系统未能生成可安全执行的数据查询。请明确查询指标、时间或对象后重试。"

    def _diag(self, diagnostics, key, value, stage):
        if diagnostics is not None:
            diagnostics["stage"] = stage
            diagnostics[key] = value

    def _append_diag(self, diagnostics, key, value, stage):
        if diagnostics is not None:
            diagnostics["stage"] = stage
            diagnostics[key].append(value)

    @staticmethod
    def _ensure_within_total_timeout(deadline: float) -> None:
        if time.monotonic() >= deadline:
            raise QueryTotalTimeoutError("查询处理超过总时限")

    async def _try_exact_example_fallback(self, request_id, request, audit_base, started, diagnostics):
        example = self.catalog.exact_example(request.question)
        if example is None:
            return None
        if diagnostics is not None:
            diagnostics["fallback"] = {"attempted": True, "exact_question_match": True, "used": False}
        try:
            with self._measure_stage(request_id, "sql_guard_example_fallback"):
                validated = self.guard.validate(example["sql"])
            result = await self._execute(
                request_id, validated, diagnostics, "execution_example_fallback"
            )
        except (SqlValidationError, QueryExecutionError):
            return None
        if diagnostics is not None:
            diagnostics["fallback"]["used"] = True
        fallback_plan = QueryPlan(
            original_question=request.question,
            query_type="aggregation",
            table_hints=sorted(validated.tables),
            required_outputs=[request.question],
        )
        response = self._success(request_id, request.question, fallback_plan, self.catalog.routing_decision(request.question), validated.tables, result, self._sources(validated.tables), limitations=[], diagnostics=diagnostics, audit_base=audit_base, started=started)
        response.warnings.insert(0, "LLM_FALLBACK_EXAMPLE")
        return response

    def health(self):
        database_state = "unhealthy"
        if self.executor.db_path.is_file():
            try:
                with sqlite3.connect(f"file:{self.executor.db_path.as_posix()}?mode=ro", uri=True) as connection:
                    connection.execute("SELECT 1").fetchone()
                database_state = "healthy"
            except sqlite3.DatabaseError:
                pass
        llm_state = "configured" if getattr(self.llm, "is_configured", False) else "missing"
        response = {"status": "healthy" if database_state == "healthy" and llm_state == "configured" else "degraded", "checks": {"database": database_state, "llm": llm_state}}
        provider_pool = getattr(self.llm, "provider_pool", None)
        if provider_pool is not None:
            response["llm_providers"] = provider_pool.snapshot()
        return response

    async def aclose(self):
        close = getattr(self.llm, "aclose", None)
        if close is not None:
            await close()
