const form=document.querySelector('#queryForm');const input=document.querySelector('#question');const send=document.querySelector('#sendButton');const conversation=document.querySelector('#conversation');const details=document.querySelector('#runDetails');const runStatus=document.querySelector('#runStatus');const copyRequestId=document.querySelector('#copyRequestId');const welcomeMarkup=conversation.innerHTML;let currentRequestId='';
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function setStatus(text,type){runStatus.textContent=text;runStatus.className=`status ${type}`}
function recentQuestions(){try{return JSON.parse(sessionStorage.getItem('recentQuestions')||'[]')}catch{return []}}
function saveRecentQuestion(question){const items=[question,...recentQuestions().filter(item=>item!==question)].slice(0,5);sessionStorage.setItem('recentQuestions',JSON.stringify(items))}
function renderRecentQuestions(){const container=document.querySelector('#recentQuestions');const list=document.querySelector('#recentQuestionList');if(!container||!list)return;const items=recentQuestions();container.hidden=!items.length;list.innerHTML=items.map(item=>`<button class="recent-question" type="button" data-recent-question="${escapeHtml(item)}">${escapeHtml(item)}</button>`).join('');list.querySelectorAll('[data-recent-question]').forEach(button=>button.onclick=()=>ask(button.dataset.recentQuestion));document.querySelector('#clearHistory').onclick=()=>{sessionStorage.removeItem('recentQuestions');renderRecentQuestions()}}
function resetConversation(){if(send.disabled)return;sessionId=null;sessionStorage.removeItem('querySessionId');conversation.innerHTML=welcomeMarkup;details.className='empty-details';details.innerHTML='<div class="empty-icon">i</div><p>提交问题后，这里会显示请求编号、数据范围、来源和限制。</p>';currentRequestId='';copyRequestId.disabled=true;setStatus('待查询','idle');bindQuestionButtons();renderRecentQuestions();input.value='';input.focus()}
function bindQuestionButtons(){document.querySelectorAll('[data-question]').forEach(button=>button.onclick=()=>{queryStartedAt=Date.now();ask(button.dataset.question)})}
function appendMessage(role,content){const el=document.createElement('article');el.className=`message ${role}`;el.innerHTML=`<p class="message-label">${role==='user'?'你':'数据助手'}</p><div class="bubble">${content}</div>`;conversation.appendChild(el);conversation.scrollTop=conversation.scrollHeight;return el}
const commonLabels={total_capacity_mw:'总装机容量（MW）',total_count:'总数量',project_count:'项目数量',station_count:'场站数量',county:'区县',project_type:'项目类型'};
function labels(data){return Object.fromEntries((data?.schema||[]).map(column=>[column.name,commonLabels[column.name]||column.semantic_label||column.name]))}
function units(data){return Object.fromEntries((data?.schema||[]).filter(column=>column.unit).map(column=>[column.name,column.unit]))}
function displayValue(value,unit){if(value==null)return '—';return `${escapeHtml(value)}${unit?` ${escapeHtml(unit)}`:''}`}
function table(data){const rows=data?.rows;if(!rows?.length)return '<p>当前合法筛选条件下未匹配到记录。</p>';const columns=Object.keys(rows[0]);const names=labels(data);const columnUnits=units(data);return `<div class="result-table-wrap"><table class="result-table"><thead><tr>${columns.map(c=>`<th>${escapeHtml(names[c]||c)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(c=>`<td>${displayValue(row[c],columnUnits[c])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function summary(data){const entries=Object.entries(data?.summary||{});const names=labels(data);const columnUnits=units(data);if(data?.result_status==='no_match')return '当前条件下没有匹配数据。';if(entries.length===1){const [key,value]=entries[0];return `${escapeHtml(names[key]||key)}：<strong>${displayValue(value,columnUnits[key])}</strong>`}return data?.rows?.length===1?Object.entries(data.rows[0]).map(([k,v])=>`${escapeHtml(names[k]||k)}：<strong>${displayValue(v,columnUnits[k])}</strong>`).join('，'):`返回 ${data?.rows?.length||0} 条结果。`}
const toolLabels={llm:'模型调用',metadata_catalog:'数据目录',sql_guard:'安全检查',sqlite_readonly:'只读数据库',agent:'Agent'};
const warningLabels={RESULT_TRUNCATED:'结果超过展示上限，当前仅显示前部分记录。',NO_DATA:'当前查询没有返回记录。',NO_DATA_AFTER_VALID_FILTER:'合法筛选条件下没有匹配数据。'};
function warningText(value){return warningLabels[value]||value}
function coverageMarkup(payload){const coverage=payload.coverage;if(!coverage)return '';const names=labels(payload.data);const columnUnits=units(payload.data);const format=item=>`${escapeHtml(names[item]||item)}${columnUnits[item]?`（${escapeHtml(columnUnits[item])}）`:''}`;return `<div class="detail-group"><h3>查询口径</h3><p>数据范围：${escapeHtml(coverage.applied_scope)}</p>${coverage.dimensions?.length?`<p>查询维度：${coverage.dimensions.map(format).join('、')}</p>`:''}${coverage.measures?.length?`<p>返回指标：${coverage.measures.map(format).join('、')}</p>`:''}</div>`}
function eventMetadata(event){const items=[];if(event.tool)items.push(toolLabels[event.tool]||event.tool);if(event.provider||event.model)items.push([event.provider,event.model].filter(Boolean).join(' / '));if(event.total_tokens!=null)items.push(`${event.total_tokens} tokens`);if(event.rule_versions?.length)items.push(`规则 ${event.rule_versions.join('、')}`);return items.length?`<span class="event-meta">${items.map(item=>`<span>${escapeHtml(item)}</span>`).join('')}</span>`:''}
function compactEvents(events){const compact=[];for(const event of events){const index=compact.findIndex(item=>item.stage===event.stage);if(index>=0)compact[index]=event;else compact.push(event)}return compact}
function timelineMarkup(events){return `<ol class="timeline">${compactEvents(events).map(event=>`<li class="${event.status}"><span class="event-summary">${escapeHtml(event.summary.replace(/完成$/,'').replace(/中$/,''))}</span>${event.duration_ms==null?'':`<small>${event.duration_ms} ms</small>`}${eventMetadata(event)}</li>`).join('')}</ol>`}
function runMetrics(events){const completed=compactEvents(events);const duration=completed.reduce((total,event)=>total+(event.duration_ms||0),0);const modelCalls=completed.filter(event=>event.tool==='llm'&&event.status==='completed').length;return `<div class="run-metrics"><span><strong>${duration}</strong> ms 阶段耗时</span><span><strong>${modelCalls}</strong> 次模型调用</span></div>`}
function renderDetails(payload,events=[]){const sources=payload.sources||[];const limitations=payload.limitations||[];currentRequestId=payload.request_id||'';copyRequestId.disabled=!currentRequestId;details.className='';details.innerHTML=`<div class="detail-group"><h3>请求编号</h3><p class="request-id">${escapeHtml(payload.request_id)}</p>${events.length?runMetrics(events):''}</div>${events.length?`<div class="detail-group"><h3>执行过程</h3>${timelineMarkup(events)}</div>`:''}${coverageMarkup(payload)}<div class="detail-group"><h3>数据来源</h3>${sources.length?`<ul>${sources.map(s=>`<li>${escapeHtml(s.dataset)}${s.version?` · ${escapeHtml(s.version)}`:''}${s.data_as_of?`<br>数据截至 ${escapeHtml(s.data_as_of)}`:''}</li>`).join('')}</ul>`:'<p>未返回来源信息</p>'}</div><div class="detail-group"><h3>限制与提示</h3>${limitations.length||payload.warnings?.length?`<ul>${[...limitations,...(payload.warnings||[]).map(warningText)].map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`:'<p>本次运行无额外限制</p>'}</div>`}
function renderProgress(events){details.className='';details.innerHTML=`<div class="run-summary"><p class="request-id">${escapeHtml(events[0]?.request_id||'正在创建请求')}</p></div><div class="detail-group"><h3>执行过程</h3>${timelineMarkup(events)}</div>`}
let sessionId=sessionStorage.getItem('querySessionId')||null;
async function streamQuery(question,onProgress){const response=await fetch('/api/v1/query-energy-data/events',{method:'POST',headers:{'Content-Type':'application/json','Accept':'text/event-stream'},body:JSON.stringify({question,...(sessionId?{session_id:sessionId}:{})})});if(!response.ok)throw new Error(`HTTP ${response.status}`);const reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';let result=null;while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const blocks=buffer.split('\n\n');buffer=blocks.pop()||'';for(const block of blocks){let type='message';let data='';for(const line of block.split('\n')){if(line.startsWith('event:'))type=line.slice(6).trim();if(line.startsWith('data:'))data+=line.slice(5).trim()}if(!data)continue;const payload=JSON.parse(data);if(type==='progress')onProgress(payload);if(type==='result')result=payload}if(done)break}if(!result)throw new Error('SSE 结果缺失');if(result.session_id){sessionId=result.session_id;sessionStorage.setItem('querySessionId',sessionId)}return result}
async function ask(question){saveRecentQuestion(question);document.querySelector('.welcome')?.remove();appendMessage('user',escapeHtml(question));const loading=appendMessage('assistant','<div class="loading" aria-label="正在查询"><i></i><i></i><i></i></div>');send.disabled=true;setStatus('查询中','running');const events=[];details.innerHTML='<div class="empty-details"><p>正在创建查询任务…</p></div>';try{const payload=await streamQuery(question,event=>{events.push(event);renderProgress(events)});loading.remove();renderDetails(payload,events);if(payload.success){appendMessage('assistant',`<div class="answer-title">${summary(payload.data)}</div>${table(payload.data)}<p class="answer-meta">数据时间：${escapeHtml(payload.data?.data_as_of||'以当前数据快照为准')}</p>`);setStatus('已完成','success')}else{const clarification=payload.error?.code==='CLARIFICATION_REQUIRED';appendMessage('assistant',`<div class="answer-title">${clarification?'需要补充条件':'本次查询未完成'}</div><p>${escapeHtml(payload.error?.message||'服务返回了未知错误。')}</p><p class="answer-meta">请求编号：${escapeHtml(payload.request_id)}</p>`);setStatus(clarification?'待补充':'失败','error')}}catch(error){loading.remove();appendMessage('assistant','<div class="answer-title">暂时无法连接查询服务</div><p>请确认服务正在运行后重试。</p>');details.innerHTML='<div class="empty-details"><p>服务连接失败</p></div>';setStatus('连接失败','error')}finally{queryStartedAt=0;send.disabled=false;input.focus()}}
form.addEventListener('submit',event=>{event.preventDefault();const value=input.value.trim();if(!value)return;input.value='';input.style.height='auto';ask(value)});bindQuestionButtons();input.addEventListener('input',()=>{input.style.height='auto';input.style.height=`${Math.min(input.scrollHeight,140)}px`});input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();form.requestSubmit()}});document.querySelector('#clearConversation').onclick=resetConversation;copyRequestId.onclick=async()=>{if(!currentRequestId)return;await navigator.clipboard.writeText(currentRequestId);const original=copyRequestId.textContent;copyRequestId.textContent='已复制';setTimeout(()=>copyRequestId.textContent=original,1200)};renderRecentQuestions();
Promise.all([fetch('/health').then(r=>r.json()),fetch('/api/v1/rules/runtime').then(r=>r.json()),fetch('/api/v1/evaluations/readiness').then(r=>r.json())]).then(([health,rules,readiness])=>{const healthy=health.status==='healthy';document.querySelector('#healthDot').className=healthy?'ok':'bad';document.querySelector('#healthText').textContent=healthy?'服务可用':'服务配置不完整';const database=document.querySelector('#databaseState');database.textContent=health.checks?.database==='healthy'?'在线 · 只读':'不可用';database.className=health.checks?.database==='healthy'?'good':'bad';const providers=health.llm_providers||[];document.querySelector('#providerState').textContent=providers.length?`${providers.length} 个可用`:'已配置';document.querySelector('#providerState').className='good';document.querySelector('#ruleState').textContent=`${rules.length} 条已生效`;document.querySelector('#ruleState').className='good';document.querySelector('#releaseState').textContent=readiness.ready_for_release?'可以发布':'尚未通过';document.querySelector('#releaseState').className=readiness.ready_for_release?'good':'warn'}).catch(()=>{document.querySelector('#healthDot').className='bad';document.querySelector('#healthText').textContent='服务不可用';['databaseState','providerState','ruleState','releaseState'].forEach(id=>{document.querySelector(`#${id}`).textContent='无法获取';document.querySelector(`#${id}`).className='bad'})});
let queryStartedAt=0;setInterval(()=>{if(runStatus?.classList.contains('running')&&queryStartedAt&&Date.now()-queryStartedAt>15000)runStatus.textContent='模型仍在处理，复杂问题可能需要更久'},1000);
form.addEventListener('submit',()=>{queryStartedAt=Date.now()});
