const list=document.querySelector('#ruleList');const dialog=document.querySelector('#ruleDialog');const form=document.querySelector('#ruleForm');const tableSelect=document.querySelector('#scopeTables');let rules=[];let gates=new Map();let filter='all';
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const split=value=>value.split(/[，,；;]/).map(item=>item.trim()).filter(Boolean);
async function api(path,options={},retried=false){const key=sessionStorage.getItem('adminKey')||'';const response=await fetch(path,{headers:{'Content-Type':'application/json',...(key?{'X-Admin-Key':key}:{}),...(options.headers||{})},...options});if(response.status===401&&!retried){const entered=prompt('请输入管理访问密钥');if(entered){sessionStorage.setItem('adminKey',entered);return api(path,options,true)}}if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail||`请求失败 (${response.status})`)}return response.json()}
function render(){const shown=filter==='all'?rules:rules.filter(rule=>rule.status===filter);document.querySelector('#count').textContent=`${shown.length} 个版本`;list.innerHTML=shown.length?shown.map(rule=>{const gate=gates.get(rule.id);const gateText=gate?(gate.passed?`评测通过 ${(gate.score*100).toFixed(0)}%`:`评测未通过 ${(gate.score*100).toFixed(0)}%`):'尚未评测';return `<article class="rule"><div><h2>${escapeHtml(rule.payload.name)}</h2><p>${escapeHtml(rule.payload.description)}</p></div><div class="meta"><strong>${escapeHtml(rule.payload.metric)}</strong> · ${escapeHtml(rule.payload.unit)}<br>${rule.payload.scope_tables.map(escapeHtml).join('、')}<br>${rule.status==='draft'?escapeHtml(gateText):''}</div><span class="badge ${rule.status}">${{published:'已发布',draft:'草稿',archived:'已归档'}[rule.status]}</span><div class="actions">${rule.status==='draft'?`<button data-action="validate" data-id="${rule.id}">校验</button><button data-action="evaluate" data-id="${rule.id}">运行评测</button><button data-action="publish" data-id="${rule.id}">发布</button>`:''}${rule.status==='archived'?`<button data-action="rollback" data-key="${rule.rule_key}" data-version="${rule.version}">回滚到 v${rule.version}</button>`:''}<span>v${rule.version}</span></div></article>`}).join(''):'<p class="empty">当前没有规则版本</p>'}
async function load(){const [ruleData,gateData]=await Promise.all([api('/api/v1/rules'),api('/api/v1/rules/evaluation-gates')]);rules=ruleData;gates=new Map(gateData.map(gate=>[gate.rule_id,gate]));render()}
async function loadCatalog(){const data=await api('/api/v1/rules/catalog');tableSelect.innerHTML=data.tables.map(table=>`<option value="${escapeHtml(table.name)}">${escapeHtml(table.dataset)} (${escapeHtml(table.name)})</option>`).join('')}
async function loadRuntimeRules(){const items=await api('/api/v1/rules/runtime');document.querySelector('#runtimeCount').textContent=`${items.length} 条生效`;document.querySelector('#runtimeRules').innerHTML=items.length?items.map(item=>`<details class="runtime-rule"><summary><strong>${escapeHtml(item.name)}</strong><span>${item.scope_tables.length?item.scope_tables.map(escapeHtml).join('、'):'全局规则'}</span></summary><p>${escapeHtml(item.content)}</p><small>来源：系统配置 · ${escapeHtml(item.id)}</small></details>`).join(''):'<p class="empty-inline">当前没有系统生效规则</p>'}
document.querySelector('#newRule').onclick=()=>{form.reset();document.querySelector('#formError').textContent='';dialog.showModal()};document.querySelector('#closeDialog').onclick=()=>dialog.close();document.querySelector('#cancelDialog').onclick=()=>dialog.close();
document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(item=>item.classList.remove('active'));button.classList.add('active');filter=button.dataset.filter;render()});
form.addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(form);const selected=[...tableSelect.selectedOptions].map(option=>option.value);const payload={rule_key:data.get('rule_key'),name:data.get('name'),description:data.get('description'),business_objects:split(data.get('business_objects')),metric:data.get('metric'),dimensions:split(data.get('dimensions')),scope_tables:selected,required_fields:{},calculation:data.get('calculation'),unit:data.get('unit'),constraints:split(data.get('constraints')),exceptions:[],examples:split(data.get('examples')),counter_examples:split(data.get('counter_examples'))};try{await api('/api/v1/rules',{method:'POST',body:JSON.stringify(payload)});dialog.close();await load()}catch(error){document.querySelector('#formError').textContent=error.message}});
list.addEventListener('click',async event=>{const button=event.target.closest('button[data-action]');if(!button)return;const original=button.textContent;try{button.disabled=true;if(button.dataset.action==='validate'){const result=await api(`/api/v1/rules/${button.dataset.id}/validate`,{method:'POST'});alert(result.valid?'校验通过':[...result.issues,...result.conflicts].join('\n'))}if(button.dataset.action==='evaluate'){button.textContent='评测中…';const run=await api(`/api/v1/rules/${button.dataset.id}/evaluate`,{method:'POST'});alert(`评测完成：${run.passed}/${run.total} 通过`)}if(button.dataset.action==='publish')await api(`/api/v1/rules/${button.dataset.id}/publish`,{method:'POST'});if(button.dataset.action==='rollback')await api(`/api/v1/rules/${button.dataset.key}/rollback/${button.dataset.version}`,{method:'POST'});await load()}catch(error){alert(error.message)}finally{button.disabled=false;button.textContent=original}});
Promise.all([load(),loadCatalog(),loadRuntimeRules()]).catch(error=>{list.innerHTML=`<p class="empty">${escapeHtml(error.message)}</p>`});
